/**
 * Supabase database types.
 *
 * Hand-written to match web/supabase/migrations/0001_init.sql for now.
 * Will be regenerated by `supabase gen types typescript --linked` once the
 * Supabase CLI is logged in (see user/06-next-steps-vercel-and-supabase.md
 * and the next step in user/07-apply-first-migration.md).
 *
 * Source of truth: claude/architecture/database-schema.md
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ─── Enums ────────────────────────────────────────────────────────────────
export type ProfileRole = "owner" | "admin" | "editor" | "viewer";

export type StockStatus =
  | "in_stock"
  | "low_stock"
  | "out_of_stock"
  | "made_to_order"
  | "unknown";

export type ProductSource =
  | "manual"
  | "justkraft_seed"
  | "csv_import"
  | "ai_assisted";

export type ReviewStatus =
  | "draft"
  | "needs_review"
  | "ready_to_publish"
  | "published"
  | "archived";

export type AttributeType = "text" | "number" | "boolean" | "select";

// ─── Table row shapes ────────────────────────────────────────────────────
export interface ProfileRow {
  id: string;
  role: ProfileRole;
  full_name: string | null;
  created_at: string;
  updated_at: string;
}

export interface CategoryRow {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  parent_id: string | null;
  sort_order: number;
  image_url: string | null;
  meta_title: string | null;
  meta_description: string | null;
  deleted_at: string | null;
  deleted_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface ProductRow {
  id: string;
  sku: string;
  slug: string;
  name: string;
  description: string | null;
  short_description: string | null;
  category_id: string | null;
  base_price_inr: number | null;
  compare_at_price_inr: number | null;
  stock_status: StockStatus;
  stock_quantity: number | null;
  low_stock_threshold: number;
  allow_backorder: boolean;
  reserved_quantity: number;
  min_order_qty: number;
  max_order_qty: number | null;
  is_published: boolean;
  review_status: ReviewStatus;
  is_featured: boolean;
  source: ProductSource;
  source_url: string | null;
  meta_title: string | null;
  meta_description: string | null;
  canonical_url: string | null;
  deleted_at: string | null;
  deleted_by: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
}

// ─── Insert / Update shapes (defaults marked optional) ────────────────────
export type ProfileInsert = {
  id: string;
  role?: ProfileRole;
  full_name?: string | null;
};
export type ProfileUpdate = Partial<ProfileInsert>;

export type CategoryInsert = {
  id?: string;
  slug: string;
  name: string;
  description?: string | null;
  parent_id?: string | null;
  sort_order?: number;
  image_url?: string | null;
  meta_title?: string | null;
  meta_description?: string | null;
  deleted_at?: string | null;
  deleted_by?: string | null;
};
export type CategoryUpdate = Partial<CategoryInsert>;

export type ProductInsert = {
  id?: string;
  sku: string;
  slug: string;
  name: string;
  description?: string | null;
  short_description?: string | null;
  category_id?: string | null;
  base_price_inr?: number | null;
  compare_at_price_inr?: number | null;
  stock_status?: StockStatus;
  stock_quantity?: number | null;
  low_stock_threshold?: number;
  allow_backorder?: boolean;
  reserved_quantity?: number;
  min_order_qty?: number;
  max_order_qty?: number | null;
  is_published?: boolean;
  review_status?: ReviewStatus;
  is_featured?: boolean;
  source?: ProductSource;
  source_url?: string | null;
  meta_title?: string | null;
  meta_description?: string | null;
  canonical_url?: string | null;
  created_by?: string | null;
  updated_by?: string | null;
};
export type ProductUpdate = Partial<ProductInsert>;

export interface AttributeDefinitionRow {
  id: string;
  slug: string;
  name: string;
  type: AttributeType;
  unit: string | null;
  applies_to_category_id: string | null;
  options_json: Json | null;
  is_filterable: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface ProductAttributeRow {
  product_id: string;
  attribute_id: string;
  value_text: string | null;
  value_number: number | null;
  value_boolean: boolean | null;
  created_at: string;
  updated_at: string;
}

export type AttributeDefinitionInsert = {
  id?: string;
  slug: string;
  name: string;
  type: AttributeType;
  unit?: string | null;
  applies_to_category_id?: string | null;
  options_json?: Json | null;
  is_filterable?: boolean;
  sort_order?: number;
};
export type AttributeDefinitionUpdate = Partial<AttributeDefinitionInsert>;

export type ProductAttributeInsert = {
  product_id: string;
  attribute_id: string;
  value_text?: string | null;
  value_number?: number | null;
  value_boolean?: boolean | null;
};
export type ProductAttributeUpdate = Partial<ProductAttributeInsert>;

// ─── Database type wrapper used by Supabase client ───────────────────────
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
      };
      categories: {
        Row: CategoryRow;
        Insert: CategoryInsert;
        Update: CategoryUpdate;
      };
      products: {
        Row: ProductRow;
        Insert: ProductInsert;
        Update: ProductUpdate;
      };
      attribute_definitions: {
        Row: AttributeDefinitionRow;
        Insert: AttributeDefinitionInsert;
        Update: AttributeDefinitionUpdate;
      };
      product_attributes: {
        Row: ProductAttributeRow;
        Insert: ProductAttributeInsert;
        Update: ProductAttributeUpdate;
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_admin: { Args: Record<string, never>; Returns: boolean };
    };
    Enums: {
      profile_role: ProfileRole;
      stock_status: StockStatus;
      product_source: ProductSource;
      review_status: ReviewStatus;
      attribute_type: AttributeType;
    };
    CompositeTypes: Record<string, never>;
  };
}
