/**
 * Placeholder Supabase database types.
 *
 * Regenerated by P1-T01..T07 via:
 *   pnpm dlx supabase gen types typescript --linked > src/lib/db/types.gen.ts
 *
 * Until then, query results are typed as `unknown` in this codebase.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
